#-------------------------------
# General Site Settings
title: comicplan
subtitle: Eventos del mundo del cómic en España
#logo: logo.svg # You can add own logo.
logo: logo_comic.png # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Comicplan
  image: logo_comicplan.png
  say-hello: Hola, somos <strong>comicplan.com</strong>
  bio: Aquí encontraras los <strong>eventos del mundo del cómic</strong> en España y posts referentes a los mismos. Lee mucho y <strong>no te pierdas ningun evento!</strong>


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
chrome: https://comicplan.com # Add your Chrome handle
whatsapp: https://t.me/comicplan # Add your Telegram handle
instagram: https://instagram.com/comicplan # Add your Instagram handle
github: https://github.com/malambra/comicCalendar # Add your
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
